import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import * as dotenv from "dotenv";
dotenv.config();

const PROPERTIES = [
  {
    title: "Cobertura Duplex Frente Mar — Jurerê Internacional",
    description: "Deslumbrante cobertura duplex com vista panorâmica para o mar em Jurerê Internacional, o bairro mais exclusivo de Florianópolis. Com 4 suítes, terraço privativo, piscina e área gourmet, este imóvel representa o ápice do luxo litorâneo. Acabamentos premium, automação residencial completa e segurança 24h.",
    price: "4800000.00",
    area: "320.00",
    bedrooms: 4,
    bathrooms: 5,
    parkingSpots: 3,
    type: "penthouse",
    city: "Florianópolis",
    state: "SC",
    neighborhood: "Jurerê Internacional",
    address: "Av. dos Búzios, 1000 — Jurerê Internacional",
    latitude: -27.4398,
    longitude: -48.5019,
    beachDistance: 30,
    features: JSON.stringify(["Piscina", "Varanda", "Vista para o mar", "Área gourmet", "Portaria 24h", "Elevador", "Sauna", "Academia"]),
    coverImage: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    ]),
    status: "available",
    featured: true,
    yearBuilt: 2022,
    condoFee: "2800.00",
    iptu: "12000.00",
  },
  {
    title: "Apartamento Beira-Mar — Balneário Camboriú",
    description: "Apartamento de alto padrão na Avenida Atlântica de Balneário Camboriú, com vista direta para o mar. 3 suítes, sala ampla com pé-direito duplo, cozinha gourmet integrada. Condomínio com piscina, academia, spa e salão de festas. Localização privilegiada a poucos passos da praia central.",
    price: "2950000.00",
    area: "185.00",
    bedrooms: 3,
    bathrooms: 3,
    parkingSpots: 2,
    type: "apartment",
    city: "Balneário Camboriú",
    state: "SC",
    neighborhood: "Centro",
    address: "Av. Atlântica, 2500 — Centro",
    latitude: -26.9906,
    longitude: -48.6348,
    beachDistance: 10,
    features: JSON.stringify(["Piscina", "Academia", "Varanda", "Vista para o mar", "Portaria 24h", "Elevador", "Spa", "Salão de festas"]),
    coverImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    ]),
    status: "available",
    featured: true,
    yearBuilt: 2021,
    condoFee: "1800.00",
    iptu: "8400.00",
  },
  {
    title: "Casa de Luxo com Piscina — Búzios",
    description: "Espetacular casa de luxo em Búzios com piscina privativa e vista para o mar. 5 quartos, sendo 4 suítes, sala de estar e jantar integradas, cozinha americana, área gourmet completa com churrasqueira. Jardim tropical, deck com piscina infinita e acesso direto à praia privativa.",
    price: "5200000.00",
    area: "450.00",
    bedrooms: 5,
    bathrooms: 6,
    parkingSpots: 4,
    type: "house",
    city: "Búzios",
    state: "RJ",
    neighborhood: "Ferradura",
    address: "Estrada da Ferradura, 500",
    latitude: -22.7469,
    longitude: -41.8819,
    beachDistance: 80,
    features: JSON.stringify(["Piscina", "Churrasqueira", "Varanda", "Vista para o mar", "Jardim", "Área gourmet"]),
    coverImage: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    ]),
    status: "available",
    featured: true,
    yearBuilt: 2019,
    condoFee: null,
    iptu: "18000.00",
  },
  {
    title: "Apartamento 2 Quartos — Praia de Ingleses",
    description: "Apartamento moderno a 200m da Praia dos Ingleses, em Florianópolis. 2 quartos, sala integrada com varanda, cozinha americana. Condomínio com piscina e churrasqueira. Ótima opção para moradia ou investimento em temporada.",
    price: "680000.00",
    area: "72.00",
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 1,
    type: "apartment",
    city: "Florianópolis",
    state: "SC",
    neighborhood: "Ingleses",
    address: "Rua das Gaivotas, 300",
    latitude: -27.4319,
    longitude: -48.3978,
    beachDistance: 200,
    features: JSON.stringify(["Piscina", "Churrasqueira", "Varanda", "Portaria 24h"]),
    coverImage: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    images: JSON.stringify(["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80"]),
    status: "available",
    featured: false,
    yearBuilt: 2018,
    condoFee: "650.00",
    iptu: "2400.00",
  },
  {
    title: "Terreno Frente Mar — Angra dos Reis",
    description: "Terreno plano com 1.200m² de frente para o mar em Angra dos Reis. Localização privilegiada em condomínio fechado de alto padrão, com infraestrutura completa. Ideal para construção de casa de luxo ou pousada boutique. Documentação regularizada.",
    price: "3800000.00",
    area: "1200.00",
    bedrooms: 0,
    bathrooms: 0,
    parkingSpots: 0,
    type: "land",
    city: "Angra dos Reis",
    state: "RJ",
    neighborhood: "Praia do Bonfim",
    address: "Condomínio Portobello",
    latitude: -23.0067,
    longitude: -44.3181,
    beachDistance: 5,
    features: JSON.stringify(["Vista para o mar", "Portaria 24h"]),
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80",
    images: JSON.stringify(["https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80"]),
    status: "available",
    featured: false,
    yearBuilt: null,
    condoFee: "1200.00",
    iptu: "6000.00",
  },
  {
    title: "Penthouse com Rooftop — Balneário Camboriú",
    description: "Penthouse exclusivo no topo de um dos edifícios mais altos de Balneário Camboriú. Vista 360° para o mar e a cidade. 4 suítes, rooftop privativo com piscina aquecida, sala de cinema, adega climatizada. Acabamento de altíssimo padrão com materiais importados.",
    price: "8500000.00",
    area: "520.00",
    bedrooms: 4,
    bathrooms: 6,
    parkingSpots: 4,
    type: "penthouse",
    city: "Balneário Camboriú",
    state: "SC",
    neighborhood: "Barra Sul",
    address: "Av. do Estado, 3000 — Barra Sul",
    latitude: -27.0013,
    longitude: -48.6293,
    beachDistance: 150,
    features: JSON.stringify(["Piscina", "Academia", "Sauna", "Spa", "Varanda", "Vista para o mar", "Portaria 24h", "Elevador", "Área gourmet"]),
    coverImage: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    images: JSON.stringify([
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    ]),
    status: "available",
    featured: true,
    yearBuilt: 2023,
    condoFee: "4500.00",
    iptu: "24000.00",
  },
  {
    title: "Casa Triplex — Ilhabela",
    description: "Casa triplex em Ilhabela com acesso direto à praia particular. 3 suítes, sala de estar com lareira, cozinha gourmet, área de lazer completa com piscina, sauna e churrasqueira. Rodeada pela Mata Atlântica com vista para o mar. Imóvel único em uma das ilhas mais preservadas do Brasil.",
    price: "2200000.00",
    area: "280.00",
    bedrooms: 3,
    bathrooms: 4,
    parkingSpots: 2,
    type: "house",
    city: "Ilhabela",
    state: "SP",
    neighborhood: "Perequê",
    address: "Rua das Palmeiras, 150",
    latitude: -23.7783,
    longitude: -45.3569,
    beachDistance: 20,
    features: JSON.stringify(["Piscina", "Sauna", "Churrasqueira", "Varanda", "Vista para o mar", "Jardim"]),
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    images: JSON.stringify(["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80"]),
    status: "available",
    featured: false,
    yearBuilt: 2017,
    condoFee: null,
    iptu: "9600.00",
  },
  {
    title: "Apartamento Studio — Maceió",
    description: "Studio moderno e funcional a 50m da Praia de Pajuçara, em Maceió. Ideal para investimento em temporada. Mobiliado com acabamento de qualidade, varanda com vista para o mar. Condomínio com piscina, academia e área de lazer.",
    price: "420000.00",
    area: "45.00",
    bedrooms: 1,
    bathrooms: 1,
    parkingSpots: 1,
    type: "apartment",
    city: "Maceió",
    state: "AL",
    neighborhood: "Pajuçara",
    address: "Av. Dr. Antônio Gouveia, 800",
    latitude: -9.6658,
    longitude: -35.7353,
    beachDistance: 50,
    features: JSON.stringify(["Piscina", "Academia", "Varanda", "Vista para o mar", "Portaria 24h"]),
    coverImage: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    images: JSON.stringify(["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80"]),
    status: "available",
    featured: false,
    yearBuilt: 2020,
    condoFee: "480.00",
    iptu: "1800.00",
  },
  {
    title: "Mansão Beira-Mar — Búzios",
    description: "Mansão exclusiva em Búzios com 800m² de área construída em terreno de 2.500m² frente para o mar. 6 suítes master, piscina olímpica, quadra de tênis, heliponto, pier privativo e casa de hóspedes. Propriedade única para quem busca o máximo em exclusividade e privacidade.",
    price: "18000000.00",
    area: "800.00",
    bedrooms: 6,
    bathrooms: 8,
    parkingSpots: 6,
    type: "house",
    city: "Búzios",
    state: "RJ",
    neighborhood: "Manguinhos",
    address: "Estrada dos Búzios, 100",
    latitude: -22.7469,
    longitude: -41.8819,
    beachDistance: 5,
    features: JSON.stringify(["Piscina", "Sauna", "Spa", "Churrasqueira", "Varanda", "Vista para o mar", "Jardim", "Área gourmet", "Quadra esportiva"]),
    coverImage: "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80",
    images: JSON.stringify(["https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80"]),
    status: "available",
    featured: true,
    yearBuilt: 2020,
    condoFee: null,
    iptu: "60000.00",
  },
  {
    title: "Apartamento 3 Suítes — Praia Brava, Itajaí",
    description: "Apartamento de alto padrão na Praia Brava, em Itajaí/SC. 3 suítes com closet, sala ampla com varanda gourmet e vista para o mar. Cozinha americana com ilha. Condomínio clube com piscinas, academia, spa e restaurante. A 10 minutos de Balneário Camboriú.",
    price: "1650000.00",
    area: "145.00",
    bedrooms: 3,
    bathrooms: 3,
    parkingSpots: 2,
    type: "apartment",
    city: "Itajaí",
    state: "SC",
    neighborhood: "Praia Brava",
    address: "Av. Nereu Ramos, 1500",
    latitude: -26.9078,
    longitude: -48.6139,
    beachDistance: 100,
    features: JSON.stringify(["Piscina", "Academia", "Spa", "Varanda", "Vista para o mar", "Portaria 24h", "Elevador", "Salão de festas"]),
    coverImage: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    images: JSON.stringify(["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80"]),
    status: "available",
    featured: false,
    yearBuilt: 2022,
    condoFee: "1400.00",
    iptu: "5400.00",
  },
  {
    title: "Casa com Vista Mar — Florianópolis Sul",
    description: "Casa contemporânea com vista para o mar na Lagoa do Peri, sul de Florianópolis. 4 quartos, sala de estar com pé-direito duplo, cozinha integrada, área gourmet com churrasqueira e piscina aquecida. Terreno de 800m² com jardim paisagístico. Tranquilidade e natureza a 30 minutos do centro.",
    price: "1900000.00",
    area: "240.00",
    bedrooms: 4,
    bathrooms: 3,
    parkingSpots: 2,
    type: "house",
    city: "Florianópolis",
    state: "SC",
    neighborhood: "Pântano do Sul",
    address: "Servidão das Pedras, 50",
    latitude: -27.7897,
    longitude: -48.5099,
    beachDistance: 500,
    features: JSON.stringify(["Piscina", "Churrasqueira", "Varanda", "Vista para o mar", "Jardim", "Área gourmet"]),
    coverImage: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80",
    images: JSON.stringify(["https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80"]),
    status: "available",
    featured: false,
    yearBuilt: 2016,
    condoFee: null,
    iptu: "7200.00",
  },
  {
    title: "Flat de Luxo — Praia do Forte, Bahia",
    description: "Flat de luxo na Praia do Forte, um dos destinos mais exclusivos da Bahia. 2 suítes, sala integrada com varanda e vista para o mar. Condomínio resort com piscinas, restaurante, spa e acesso direto à praia. Perfeito para moradia ou investimento em temporada.",
    price: "890000.00",
    area: "85.00",
    bedrooms: 2,
    bathrooms: 2,
    parkingSpots: 1,
    type: "apartment",
    city: "Mata de São João",
    state: "BA",
    neighborhood: "Praia do Forte",
    address: "Av. do Farol, 200",
    latitude: -12.5773,
    longitude: -38.0048,
    beachDistance: 80,
    features: JSON.stringify(["Piscina", "Spa", "Varanda", "Vista para o mar", "Portaria 24h", "Restaurante"]),
    coverImage: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80",
    images: JSON.stringify(["https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80"]),
    status: "available",
    featured: false,
    yearBuilt: 2021,
    condoFee: "1100.00",
    iptu: "3600.00",
  },
];

async function seed() {
  const connection = await mysql.createConnection(process.env.DATABASE_URL);
  const db = drizzle(connection);

  console.log("🌊 Semeando dados de exemplo...");

  for (const prop of PROPERTIES) {
    try {
      await connection.execute(
        `INSERT INTO properties (title, description, price, area, bedrooms, bathrooms, parkingSpots, type, city, state, neighborhood, address, latitude, longitude, beachDistance, features, coverImage, images, status, featured, yearBuilt, condoFee, iptu) 
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [
          prop.title, prop.description, prop.price, prop.area,
          prop.bedrooms, prop.bathrooms, prop.parkingSpots, prop.type,
          prop.city, prop.state, prop.neighborhood, prop.address,
          prop.latitude, prop.longitude, prop.beachDistance,
          prop.features, prop.coverImage, prop.images,
          prop.status, prop.featured ? 1 : 0, prop.yearBuilt,
          prop.condoFee, prop.iptu,
        ]
      );
      console.log(`✅ ${prop.title}`);
    } catch (err) {
      console.error(`❌ Erro em ${prop.title}:`, err.message);
    }
  }

  console.log("✅ Seed concluído!");
  await connection.end();
}

seed().catch(console.error);
